### ISSUE TITLE
Crash wenn keine Artikel/Kategorien vorhanden

### ISSUE THREAD

**Issue by abra100pro** [KLXM/locked#2]
Hallo
Ich habe es versucht auf einer Site zu installieren, wo es noch keine Artikel/Kategorien gab, was zu einem Crash führte. 
Das war lokal mit MAMP - habe es nicht auf einem Live server versucht, aber nehme an, dass das keine Rolle spielt.

**Comment by alxndr-w** [comment]
Wie lautete denn die Fehlermeldung? Kannst du den Debug-Modus aktivieren und einen Sacktrace hier rein kopieren?

**Comment by skerbis** [comment]
ok , Danke für die Info

**Error:** Call to a member function getValue() on null
**File:** redaxo/src/addons/locked/boot.php
**Line:** 39

Sollte jetzt in 1.0.2 gelöst sein.
